# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FlutterBoostDemo_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  flutter_application_path = '../flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)	

  # Pods for FlutterBoostDemo_swift

  target 'FlutterBoostDemo_swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterBoostDemo_swiftUITests' do
    # Pods for testing
  end

end
