language: dart
sudo: required
dist: bionic
dart:
  - stable
  - beta
  - dev
before_script:
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - dart tool/travis.dart
