# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'FlutterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  flutter_application_path = '../flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

  target 'FlutterAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterAppUITests' do
    # Pods for testing
  end

end
